### PR TITLE
TCPTransport: switch from select.select() to selectors

### PR DESCRIPTION
**Pull request by gbanasiak**
Closes https://github.com/thespianpy/Thespian/issues/78

### CODE REVIEW

File: thespian/system/transport/errmgmt.py [hunk 1]
```diff
@@ -14,7 +14,7 @@ def err_conn_refused(errex):
 
 
 def err_send_inprogress(err):
-    return err in [errno.EINPROGRESS, errno.EAGAIN]
+    return err in [errno.EINPROGRESS, errno.EAGAIN, errno.ENOTCONN]
```
Comment (gbanasiak) [inline thespian/system/transport/errmgmt.py:17]: Required to pass `thespian/test/test_generators.py` test on MacOS. `selectors` signal socket as ready to send yet `[Errno 57] Socket is not connected` error is raised when sending in `_next_XMIT_2()`. After a slight backoff, all works fine. From what I could tell looking at packet dumps, `socket.send()` was throwing this error _after_ TCP connection was already established. What is special about this test is the use of global names combined with creation of multiple actors in quick succession.

Fun fact: This test was created after report from Rally lead developer in March 2017. Rally no longer uses global names. They were removed from Rally by Thespian lead developer in December 2017. :-)

**Comment by gbanasiak** [comment]
The switch to selectors in the proposed format comes with a noticeable performance hit. Below are the results obtained on GCP N2 instance with 16 cores and 68 GiB of RAM, with Ubuntu 22.04, Linux kernel 6.5.0-1025-gcp, Python 3.11.7.

Performance testing done with `thespian/test/test_load.py` and `examples/socketstress.py`, 3 repetitions each.

With `select.select()`:

```
$ python thespian/test/test_load.py
 10 Actors,                    Discarding              simpleSystemBase -- 0:00:00.115853 -- 17263.26/sec overall -- 172632.56 msg/sec
 10 Actors,                    Discarding              multiprocUDPBase -- 0:00:00.199563 -- 10021.90/sec overall -- 100218.98 msg/sec
 10 Actors,                    Discarding              multiprocTCPBase -- 0:00:02.336345 -- 856.04/sec overall -- 8560.38 msg/sec
 10 Actors,                    Discarding multiprocTCPBase-AdminRouting -- 0:00:02.347378 -- 852.01/sec overall -- 8520.14 msg/sec

 10 Actors,      Discard, Last Ask (2001)              simpleSystemBase -- 0:00:00.119057 -- 16798.68/sec overall -- 167986.76 msg/sec
 10 Actors, Discard, Last Ask (<timeout>)              multiprocUDPBase -- 0:00:30.265983 -- 66.08/sec overall --  660.81 msg/sec
 10 Actors,      Discard, Last Ask (2001)              multiprocTCPBase -- 0:00:02.973658 -- 672.57/sec overall -- 6725.72 msg/sec
 10 Actors,      Discard, Last Ask (2001) multiprocTCPBase-AdminRouting -- 0:00:02.566767 -- 779.19/sec overall -- 7791.90 msg/sec

 10 Actors,                        Asking              simpleSystemBase -- 0:00:00.146185 -- 13681.29/sec overall -- 136812.94 msg/sec
 10 Actors,                        Asking              multiprocUDPBase -- 0:00:04.973738 -- 402.11/sec overall -- 4021.12 msg/sec
 10 Actors,                        Asking              multiprocTCPBase -- 0:00:08.936919 -- 223.79/sec overall -- 2237.91 msg/sec
 10 Actors,                        Asking multiprocTCPBase-AdminRouting -- 0:00:09.933102 -- 201.35/sec overall -- 2013.47 msg/sec

$ python thespian/test/test_load.py
 10 Actors,                    Discarding              simpleSystemBase -- 0:00:00.115714 -- 17283.99/sec overall -- 172839.93 msg/sec
 10 Actors,                    Discarding              multiprocUDPBase -- 0:00:00.294615 -- 6788.52/sec overall -- 67885.21 msg/sec
 10 Actors,                    Discarding              multiprocTCPBase -- 0:00:02.357293 -- 848.43/sec overall -- 8484.31 msg/sec
 10 Actors,                    Discarding multiprocTCPBase-AdminRouting -- 0:00:02.644478 -- 756.29/sec overall -- 7562.93 msg/sec

 10 Actors,      Discard, Last Ask (2001)              simpleSystemBase -- 0:00:00.121263 -- 16493.08/sec overall -- 164930.77 msg/sec
 10 Actors, Discard, Last Ask (<timeout>)              multiprocUDPBase -- 0:00:30.271552 -- 66.07/sec overall --  660.69 msg/sec
 10 Actors,      Discard, Last Ask (2001)              multiprocTCPBase -- 0:00:02.983618 -- 670.33/sec overall -- 6703.27 msg/sec
 10 Actors,      Discard, Last Ask (2001) multiprocTCPBase-AdminRouting -- 0:00:03.332969 -- 600.07/sec overall -- 6000.66 msg/sec

 10 Actors,                        Asking              simpleSystemBase -- 0:00:00.146473 -- 13654.39/sec overall -- 136543.94 msg/sec
 10 Actors,                        Asking              multiprocUDPBase -- 0:00:04.891823 -- 408.85/sec overall -- 4088.46 msg/sec
 10 Actors,                        Asking              multiprocTCPBase -- 0:00:08.785903 -- 227.64/sec overall -- 2276.37 msg/sec
 10 Actors,                        Asking multiprocTCPBase-AdminRouting -- 0:00:09.832651 -- 203.40/sec overall -- 2034.04 msg/sec

$ python thespian/test/test_load.py
 10 Actors,                    Discarding              simpleSystemBase -- 0:00:00.115063 -- 17381.78/sec overall -- 173817.82 msg/sec
 10 Actors,                    Discarding              multiprocUDPBase -- 0:00:00.226867 -- 8815.74/sec overall -- 88157.38 msg/sec
 10 Actors,                    Discarding              multiprocTCPBase -- 0:00:02.587148 -- 773.05/sec overall -- 7730.52 msg/sec
 10 Actors,                    Discarding multiprocTCPBase-AdminRouting -- 0:00:02.633900 -- 759.33/sec overall -- 7593.30 msg/sec

 10 Actors,      Discard, Last Ask (2001)              simpleSystemBase -- 0:00:00.116930 -- 17104.25/sec overall -- 171042.50 msg/sec
 10 Actors,      Discard, Last Ask (1167)              multiprocUDPBase -- 0:00:00.354724 -- 5638.19/sec overall -- 56381.86 msg/sec
 10 Actors,      Discard, Last Ask (2001)              multiprocTCPBase -- 0:00:03.030366 -- 659.99/sec overall -- 6599.86 msg/sec
 10 Actors,      Discard, Last Ask (2001) multiprocTCPBase-AdminRouting -- 0:00:03.141696 -- 636.60/sec overall -- 6365.99 msg/sec

 10 Actors,                        Asking              simpleSystemBase -- 0:00:00.145370 -- 13758.00/sec overall -- 137579.97 msg/sec
 10 Actors,                        Asking              multiprocUDPBase -- 0:00:04.474104 -- 447.02/sec overall -- 4470.17 msg/sec
 10 Actors,                        Asking              multiprocTCPBase -- 0:00:07.498362 -- 266.72/sec overall -- 2667.25 msg/sec
 10 Actors,                        Asking multiprocTCPBase-AdminRouting -- 0:00:08.737539 -- 228.90/sec overall -- 2288.97 msg/sec

$ python examples/socketstress.py 300 100
socketstress with 300 worker(s) and 100 repetition(s)
creating dispatcher...
starting workers...
run!
run completed in 24.75444974600032 seconds

$ python examples/socketstress.py 300 100
socketstress with 300 worker(s) and 100 repetition(s)
creating dispatcher...
starting workers...
run!
run completed in 25.014236159999655 seconds

$ python examples/socketstress.py 300 100
socketstress with 300 worker(s) and 100 repetition(s)
creating dispatcher...
starting workers...
run!
run completed in 24.703100304000145 seconds
```

With `selectors`:

```
$ python thespian/test/test_load.py
 10 Actors,                    Discarding              simpleSystemBase -- 0:00:00.115437 -- 17325.47/sec overall -- 173254.68 msg/sec
 10 Actors,                    Discarding              multiprocUDPBase -- 0:00:00.249469 -- 8017.03/sec overall -- 80170.28 msg/sec
 10 Actors,                    Discarding              multiprocTCPBase -- 0:00:02.674457 -- 747.82/sec overall -- 7478.15 msg/sec
 10 Actors,                    Discarding multiprocTCPBase-AdminRouting -- 0:00:02.890208 -- 691.99/sec overall -- 6919.92 msg/sec

 10 Actors,      Discard, Last Ask (2001)              simpleSystemBase -- 0:00:00.121010 -- 16527.56/sec overall -- 165275.60 msg/sec
 10 Actors,       Discard, Last Ask (860)              multiprocUDPBase -- 0:00:00.279207 -- 7163.14/sec overall -- 71631.44 msg/sec
 10 Actors,      Discard, Last Ask (2001)              multiprocTCPBase -- 0:00:03.291470 -- 607.63/sec overall -- 6076.31 msg/sec
 10 Actors,      Discard, Last Ask (2001) multiprocTCPBase-AdminRouting -- 0:00:03.685736 -- 542.63/sec overall -- 5426.32 msg/sec

 10 Actors,                        Asking              simpleSystemBase -- 0:00:00.145124 -- 13781.32/sec overall -- 137813.18 msg/sec
 10 Actors,                        Asking              multiprocUDPBase -- 0:00:05.174859 -- 386.48/sec overall -- 3864.84 msg/sec
 10 Actors,                        Asking              multiprocTCPBase -- 0:00:09.912807 -- 201.76/sec overall -- 2017.59 msg/sec
 10 Actors,                        Asking multiprocTCPBase-AdminRouting -- 0:00:10.926298 -- 183.04/sec overall -- 1830.45 msg/sec

$ python thespian/test/test_load.py
 10 Actors,                    Discarding              simpleSystemBase -- 0:00:00.117395 -- 17036.50/sec overall -- 170365.01 msg/sec
 10 Actors,                    Discarding              multiprocUDPBase -- 0:00:00.204030 -- 9802.48/sec overall -- 98024.80 msg/sec
 10 Actors,                    Discarding              multiprocTCPBase -- 0:00:02.489403 -- 803.41/sec overall -- 8034.05 msg/sec
 10 Actors,                    Discarding multiprocTCPBase-AdminRouting -- 0:00:02.747055 -- 728.05/sec overall -- 7280.52 msg/sec

 10 Actors,      Discard, Last Ask (2001)              simpleSystemBase -- 0:00:00.120873 -- 16546.29/sec overall -- 165462.92 msg/sec
 10 Actors, Discard, Last Ask (<timeout>)              multiprocUDPBase -- 0:00:30.275374 -- 66.06/sec overall --  660.60 msg/sec
 10 Actors,      Discard, Last Ask (2001)              multiprocTCPBase -- 0:00:03.245753 -- 616.19/sec overall -- 6161.90 msg/sec
 10 Actors,      Discard, Last Ask (2001) multiprocTCPBase-AdminRouting -- 0:00:03.527745 -- 566.93/sec overall -- 5669.34 msg/sec

 10 Actors,                        Asking              simpleSystemBase -- 0:00:00.145196 -- 13774.48/sec overall -- 137744.84 msg/sec
 10 Actors,                        Asking              multiprocUDPBase -- 0:00:05.380196 -- 371.73/sec overall -- 3717.34 msg/sec
 10 Actors,                        Asking              multiprocTCPBase -- 0:00:10.262456 -- 194.89/sec overall -- 1948.85 msg/sec
 10 Actors,                        Asking multiprocTCPBase-AdminRouting -- 0:00:11.318871 -- 176.70/sec overall -- 1766.96 msg/sec

$ python thespian/test/test_load.py
 10 Actors,                    Discarding              simpleSystemBase -- 0:00:00.115197 -- 17361.56/sec overall -- 173615.63 msg/sec
 10 Actors,                    Discarding              multiprocUDPBase -- 0:00:00.354305 -- 5644.85/sec overall -- 56448.54 msg/sec
 10 Actors,                    Discarding              multiprocTCPBase -- 0:00:02.669223 -- 749.28/sec overall -- 7492.82 msg/sec
 10 Actors,                    Discarding multiprocTCPBase-AdminRouting -- 0:00:02.970758 -- 673.23/sec overall -- 6732.29 msg/sec

 10 Actors,      Discard, Last Ask (2001)              simpleSystemBase -- 0:00:00.118793 -- 16836.01/sec overall -- 168360.09 msg/sec
 10 Actors,      Discard, Last Ask (1405)              multiprocUDPBase -- 0:00:00.448019 -- 4464.10/sec overall -- 44640.96 msg/sec
 10 Actors,      Discard, Last Ask (2001)              multiprocTCPBase -- 0:00:03.116152 -- 641.82/sec overall -- 6418.17 msg/sec
 10 Actors,      Discard, Last Ask (2001) multiprocTCPBase-AdminRouting -- 0:00:03.914065 -- 510.98/sec overall -- 5109.78 msg/sec

 10 Actors,                        Asking              simpleSystemBase -- 0:00:00.146773 -- 13626.48/sec overall -- 136264.84 msg/sec
 10 Actors,                        Asking              multiprocUDPBase -- 0:00:05.510819 -- 362.92/sec overall -- 3629.22 msg/sec
 10 Actors,                        Asking              multiprocTCPBase -- 0:00:10.462576 -- 191.16/sec overall -- 1911.58 msg/sec
 10 Actors,                        Asking multiprocTCPBase-AdminRouting -- 0:00:11.534468 -- 173.39/sec overall -- 1733.93 msg/sec

$ python examples/socketstress.py 300 100
socketstress with 300 worker(s) and 100 repetition(s)
creating dispatcher...
starting workers...
run!
run completed in 28.845968146999894 seconds

$ python examples/socketstress.py 300 100
socketstress with 300 worker(s) and 100 repetition(s)
creating dispatcher...
starting workers...
run!
run completed in 28.571690353000122 seconds

$ python examples/socketstress.py 300 100
socketstress with 300 worker(s) and 100 repetition(s)
creating dispatcher...
starting workers...
run!
run completed in 28.137470099999973 seconds
```

Looking at the CPU profiles taken from `Dispatcher` process of `examples/socketstress.py` during long runs (`python examples/socketstress.py 300 1000`), the largest chunk of time is spent registering sockets for reads, but even selector creation and its subsequent closure is already consuming similar on-CPU time when compared with `select.select()`:

[selectors.tgz](https://github.com/user-attachments/files/18295360/selectors.tgz)

```
# select.select()
TCPTransport.py:1158 (select) - 71 stack trace samples, 1.18%

# selectors
TCPTransport.py:1153 (selector creation) - 14 stack trace samples, 0.23%
TCPTransport.py:1155 (socket registration for read) - 696 stack trace samples, 11.66% (!)
TCPTransport.py:1157 (socket registration for write) - 8 stack trace samples, 0.13%
TCPTransport.py:1158 (selector select) - not captured
TCPTransport.py:1164 (selector closure) - 99 stack trace samples, 1.66%
```

It seems that `selectors` can only perform faster than `select.select()` if selector creation, closure and socket registrations are taken out of `_runWithExpiry()` method.

**Comment by gbanasiak** [comment]
Addressing Windows test (`pytest -k multiprocTCPBase`) failures:

After addressing obvious Windows incompatibilities in https://github.com/thespianpy/Thespian/pull/81/commits/e0df29aa43d50d56c78dabb5b998162974ae2edb, https://github.com/thespianpy/Thespian/pull/81/commits/19d3f41469b3d9cba2ec9858d80696d62ab19fff and https://github.com/thespianpy/Thespian/pull/81/commits/b4fe2c099e37841d715a72969c613983c4568806, and extending the timeout in https://github.com/thespianpy/Thespian/pull/81/commits/281f5e24b20674fd03b5fa700ba12c90c64d7c87 I can still see the following failures.

From these, failures in `test_deadLettering.py` seem to have been introduced by this PR, as I can see remaining failures also with recent `main`. I will take a closer look.

```
======================================================================================== short test summary info =========================================================================================
FAILED thespian/test/test_actorFailures.py::TestFuncActorFailures::test08_DeepActorInvoluntaryTermination[multiprocTCPBase] - AssertionError: assert 'not replaced' == 'replaced'
FAILED thespian/test/test_actorFailures.py::TestFuncActorFailures::test08_DeepActorInvoluntaryTermination[multiprocTCPBase-AdminRouting] - AssertionError: assert 'not replaced' == 'replaced'
FAILED thespian/test/test_actorFailures.py::TestFuncActorFailures::test08_DeepActorInvoluntaryTermination[multiprocTCPBase-AdminRoutingTXOnly] - AssertionError: assert 'not replaced' == 'replaced'
FAILED thespian/test/test_deadLettering.py::TestFuncDeadLettering::test02_GetDeadLetter[multiprocTCPBase] - assert 0 > 0
FAILED thespian/test/test_deadLettering.py::TestFuncDeadLettering::test02_GetDeadLetter[multiprocTCPBase-AdminRouting] - assert 0 > 0
FAILED thespian/test/test_deadLettering.py::TestFuncDeadLettering::test02_GetDeadLetter[multiprocTCPBase-AdminRoutingTXOnly] - assert 0 > 0
FAILED thespian/test/test_deadLettering.py::TestFuncDeadLettering::test12_GetDeadLetterSubActor[multiprocTCPBase] - assert 0 > 0
FAILED thespian/test/test_deadLettering.py::TestFuncDeadLettering::test12_GetDeadLetterSubActor[multiprocTCPBase-AdminRouting] - assert 0 > 0
FAILED thespian/test/test_deadLettering.py::TestFuncDeadLettering::test12_GetDeadLetterSubActor[multiprocTCPBase-AdminRoutingTXOnly] - assert 0 > 0
FAILED thespian/test/test_deadLettering.py::TestFuncDeadLettering::test03_DLRegisterOnlyOnce[multiprocTCPBase] - assert 0 > 0
FAILED thespian/test/test_deadLettering.py::TestFuncDeadLettering::test03_DLRegisterOnlyOnce[multiprocTCPBase-AdminRouting] - assert 0 > 0
FAILED thespian/test/test_deadLettering.py::TestFuncDeadLettering::test03_DLRegisterOnlyOnce[multiprocTCPBase-AdminRoutingTXOnly] - assert 0 > 0
FAILED thespian/test/test_deadLettering.py::TestFuncDeadLettering::test13_DLRegisterOnlyOnce[multiprocTCPBase] - assert 0 > 0
FAILED thespian/test/test_deadLettering.py::TestFuncDeadLettering::test13_DLRegisterOnlyOnce[multiprocTCPBase-AdminRouting] - assert 0 > 0
FAILED thespian/test/test_deadLettering.py::TestFuncDeadLettering::test13_DLRegisterOnlyOnce[multiprocTCPBase-AdminRoutingTXOnly] - assert 0 > 0
FAILED thespian/test/test_deadLettering.py::TestFuncDeadLettering::test04_DLMultipleHandlers[multiprocTCPBase] - assert 0 > 0
FAILED thespian/test/test_deadLettering.py::TestFuncDeadLettering::test04_DLMultipleHandlers[multiprocTCPBase-AdminRouting] - assert 0 > 0
FAILED thespian/test/test_deadLettering.py::TestFuncDeadLettering::test04_DLMultipleHandlers[multiprocTCPBase-AdminRoutingTXOnly] - assert 0 > 0
FAILED thespian/test/test_deadLettering.py::TestFuncDeadLettering::test14_DLMultipleHandlers[multiprocTCPBase] - assert 0 > 0
FAILED thespian/test/test_deadLettering.py::TestFuncDeadLettering::test14_DLMultipleHandlers[multiprocTCPBase-AdminRouting] - assert 0 > 0
FAILED thespian/test/test_deadLettering.py::TestFuncDeadLettering::test14_DLMultipleHandlers[multiprocTCPBase-AdminRoutingTXOnly] - assert 0 > 0
FAILED thespian/test/test_deadLettering.py::TestFuncDeadLettering::test05_DLAutoRemoval[multiprocTCPBase] - assert 0 > 0
FAILED thespian/test/test_deadLettering.py::TestFuncDeadLettering::test05_DLAutoRemoval[multiprocTCPBase-AdminRouting] - assert 0 > 0
FAILED thespian/test/test_deadLettering.py::TestFuncDeadLettering::test05_DLAutoRemoval[multiprocTCPBase-AdminRoutingTXOnly] - assert 0 > 0
FAILED thespian/test/test_deadLettering.py::TestFuncDeadLettering::test15_DLAutoRemoval[multiprocTCPBase] - assert 0 > 0
FAILED thespian/test/test_deadLettering.py::TestFuncDeadLettering::test15_DLAutoRemoval[multiprocTCPBase-AdminRouting] - assert 0 > 0
FAILED thespian/test/test_deadLettering.py::TestFuncDeadLettering::test15_DLAutoRemoval[multiprocTCPBase-AdminRoutingTXOnly] - assert 0 > 0
FAILED thespian/test/test_manyActorSystems.py::TestFuncManyActorSystem::test10_requiredRequirementsPassedViaSubLevelSucceeds[multiprocTCPBase-AdminRouting] - AssertionError: assert None == 'Thanks for the Trees'
FAILED thespian/test/test_manyActorSystems.py::TestFuncManyActorSystem::test10_requiredRequirementsPassedViaSubLevelSucceeds[multiprocTCPBase-AdminRoutingTXOnly] - AssertionError: assert None == 'Thanks for the Trees'
FAILED thespian/test/test_manyActorSystems.py::TestFuncConventionDeregistration::testNotifications[multiprocTCPBase] - AssertionError: assert (2, 2) == (2, 1)
FAILED thespian/test/test_manyActorSystems.py::TestFuncConventionDeregistration::testNotifications[multiprocTCPBase-AdminRouting] - AssertionError: assert (2, 2) == (2, 1)
FAILED thespian/test/test_runcommand.py::TestRunCommand::testCommandAbort[multiprocTCPBase] - AttributeError: 'NoneType' object has no attribute 'exitcode'
FAILED thespian/test/test_runcommand.py::TestRunCommand::testCommandAbort[multiprocTCPBase-AdminRouting] - AttributeError: 'NoneType' object has no attribute 'exitcode'
FAILED thespian/test/test_runcommand.py::TestRunCommand::testCommandAbort[multiprocTCPBase-AdminRoutingTXOnly] - AttributeError: 'NoneType' object has no attribute 'exitcode'
========================================================== 34 failed, 1010 passed, 16 skipped, 1416 deselected, 3 xfailed in 4539.87s (1:15:39) ==========================================================
```

**Comment by gbanasiak** [comment]
`test_deadLettering.py` errors were caused by https://github.com/thespianpy/Thespian/pull/81/commits/e81b06b649910d0611f85a86746db9fe1912efb5. On MacOS `ENOTCONN` error can appear right after successful socket `.connect()` so I've added it to `err_send_inprogress()`. However this had hidden special handling of `ENOTCONN` on Windows where it can be used to signal refused connection - see `err_conn_refused()`, `winerror` of 10057 is an equivalent of `ENOTCONN`. I've addressed this by making `ENOTCONN` selective in `err_send_inprogress()`, i.e. Windows is not included. The alternative was to rely on retries, see https://github.com/thespianpy/Thespian/pull/81/commits/37f06fc1c52b862e173ad757732f4c5979c85acf, but that was slower.

Now I can see the following failures on Windows which are _also_ present in `master` branch. That's after increasing timeouts in `test_HAConvention` and `test_manyActorSystems` which eliminated some of the errors (again, also present in `master` branch). I think these should be addressed separately.

```
pytest -v -k multiprocTCPBase
[..]
======================================================================================== short test summary info =========================================================================================
FAILED thespian/test/test_actorFailures.py::TestFuncActorFailures::test08_DeepActorInvoluntaryTermination[multiprocTCPBase] - AssertionError: assert 'not replaced' == 'replaced'
FAILED thespian/test/test_actorFailures.py::TestFuncActorFailures::test08_DeepActorInvoluntaryTermination[multiprocTCPBase-AdminRouting] - AssertionError: assert 'not replaced' == 'replaced'
FAILED thespian/test/test_actorFailures.py::TestFuncActorFailures::test08_DeepActorInvoluntaryTermination[multiprocTCPBase-AdminRoutingTXOnly] - AssertionError: assert 'not replaced' == 'replaced'
FAILED thespian/test/test_manyActorSystems.py::TestFuncConventionDeregistration::testNotifications[multiprocTCPBase] - AssertionError: assert (2, 2) == (2, 1)
FAILED thespian/test/test_manyActorSystems.py::TestFuncConventionDeregistration::testNotifications[multiprocTCPBase-AdminRouting] - AssertionError: assert (2, 2) == (2, 1)
FAILED thespian/test/test_runcommand.py::TestRunCommand::testCommandAbort[multiprocTCPBase] - AttributeError: 'NoneType' object has no attribute 'exitcode'
FAILED thespian/test/test_runcommand.py::TestRunCommand::testCommandAbort[multiprocTCPBase-AdminRouting] - AttributeError: 'NoneType' object has no attribute 'exitcode'
FAILED thespian/test/test_runcommand.py::TestRunCommand::testCommandAbort[multiprocTCPBase-AdminRoutingTXOnly] - AttributeError: 'NoneType' object has no attribute 'exitcode'
FAILED thespian/test/test_sourceLoading.py::TestFuncLoadSource::test02_verifyNotificationKillDoesNotBreakNotify[multiprocTCPBase] - AssertionError: assert 'GOT: good one' == None
FAILED thespian/test/test_sourceLoading.py::TestFuncLoadSource::test02_verifyNotificationKillDoesNotBreakNotify[multiprocTCPBase-AdminRouting] - AssertionError: assert 'GOT: good one' == None
FAILED thespian/test/test_sourceLoading.py::TestFuncLoadSource::test02_verifyNotificationKillDoesNotBreakNotify[multiprocTCPBase-AdminRoutingTXOnly] - AssertionError: assert 'GOT: good one' == None
FAILED thespian/test/test_sourceLoading.py::TestFuncLoadSource::test02_verifyNotificationOfMultipleKillOneDoesNotBreakNotify[multiprocTCPBase] - AssertionError: assert 'GOT: good one' == None
FAILED thespian/test/test_sourceLoading.py::TestFuncLoadSource::test02_verifyNotificationOfMultipleKillOneDoesNotBreakNotify[multiprocTCPBase-AdminRouting] - AssertionError: assert 'GOT: good one' == None
FAILED thespian/test/test_sourceLoading.py::TestFuncLoadSource::test02_verifyNotificationOfMultipleKillOneDoesNotBreakNotify[multiprocTCPBase-AdminRoutingTXOnly] - AssertionError: assert 'GOT: good one' == None
FAILED thespian/test/test_updateSystemCapabilities.py::TestFuncCapabilityUpdates::test06_removingColorCapabilitiesPreventsNewColorActors[multiprocTCPBase] - AssertionError: assert 'hey, green' == None
FAILED thespian/test/test_updateSystemCapabilities.py::TestFuncCapabilityUpdates::test06_removingColorCapabilitiesPreventsNewColorActors[multiprocTCPBase-AdminRouting] - AssertionError: assert 'hey, green' == None
FAILED thespian/test/test_updateSystemCapabilities.py::TestFuncCapabilityUpdates::test06_removingColorCapabilitiesPreventsNewColorActors[multiprocTCPBase-AdminRoutingTXOnly] - AssertionError: assert 'hey, green' == None
========================================================== 17 failed, 1027 passed, 16 skipped, 1416 deselected, 3 xfailed in 2662.44s (0:44:22) ==========================================================
```

Windows is generally slower than Linux and MacOS. On Windows 10, TCP tests took 44 minutes to complete, while on Linux and MacOS - 17.5 and 18 minutes respectively (all test machines with similar spec). Extra debug logs around `.select()` show that Windows often pauses longer when waiting for available socket. Again, same behavior with `master` branch. This slowness might explain why some of the tests started working just be increasing the actor's `ask()` timeouts. Perhaps some of the remaining failed tests might be explained by the same, but I did not want to invest more time into it.

---

After more test iterations I've noticed MacOS fails the following tests from time to time. The same happens in `master` branch.

```
============================================================================================================= short test summary info =============================================================================================================
FAILED thespian/test/test_actorFailures.py::TestFuncActorFailures::test_abrupt_child_exit[multiprocTCPBase] - assert None is not None
FAILED thespian/test/test_actorFailures.py::TestFuncActorFailures::test_abrupt_child_exit[multiprocTCPBase-AdminRoutingTXOnly] - assert None is not None
=============================================================================== 2 failed, 1066 passed, 9 skipped, 1642 deselected, 3 xfailed in 1081.70s (0:18:01) ================================================================================
```

The reason is `interrupt_wait()` from `TCPTransport` fails to connect to local listening socket to break `.select()` loop due to `EINPROGRESS` from a non-blocking socket.

---

@kquick I think I've reached end of the road for the simplest approach. To the best of my knowledge the PR in current form is passing all the TCP tests that are also passing in `master`.

File: thespian/system/transport/errmgmt.py (hunk 1 above)
Comment (gbanasiak) [reply thespian/system/transport/errmgmt.py]: Follow-up in https://github.com/thespianpy/Thespian/pull/81#issuecomment-2571709773.

**Comment by kquick** [comment]
The performance impact of `selectors` is a bit disappointing because the abstraction it provides is convenient.  I took a look at the implementation and there's nothing obvious that I would attribute the slowdown to, so it's probably  an aggregation of a number of small things.  That said, you've indicate that this is an acceptable tradeoff for your purposes, and in general I would prefer correctness over performance, so I really appreciate your digging in to not only do this work, but evaluate the results and address some of the other platform issues along the way!

I'd like to make a release soon, because this also helps with the Windows regression from the recent version.  I'll wait another couple of days to see if there's any movement on the other active PR and plan to generate a release next week.
